// apps/svelte-app/src/lib/Footer.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let todosCount: number = 0;
  export let status: string | undefined;

  const dispatch = createEventDispatcher();
</script>

<footer class="flex items-center p-4 justify-between">
  <span id="todo-count">
    <strong>{todosCount}</strong> items left
  </span>

  <ul class="flex gap-4">
    <li>
      <button
        class="link hover:text-blue-400"
        class:text-blue-400={status === 'all'}
        data-status="all"
        on:click={() => dispatch('status', 'all')}
        type="button"
      >
        All
      </button>
    </li>
    <li>
      <button
        class="link hover:text-blue-400"
        class:text-blue-400={status === 'pending'}
        data-status="pending"
        type="button"
        on:click={() => dispatch('status', 'pending')}
      >
        Active
      </button>
    </li>
    <li>
      <button
        class="link hover:text-blue-400"
        class:text-blue-400={status === 'done'}
        data-status="done"
        type="button"
        on:click={() => dispatch('status', 'done')}
      >
        Completed
      </button>
    </li>
  </ul>

  <div />
</footer>

// apps/react-todoapp/src/components/footer.tsx
import clsx from 'clsx';
import { ReactElement } from 'react';

export type FooterProps = {
  todosCount: number;
  status: string;
  handleStatus: (status: string) => void;
};

export function Footer({ todosCount, handleStatus, status }: FooterProps): ReactElement {
  return (
    <footer className="flex items-center p-4 justify-between">
      <span id="todo-count">
        <strong>{todosCount || 0}</strong> items left
      </span>

      <ul className="flex gap-4">
        <li>
          <button
            className={clsx(['link hover:text-blue-400', status === 'all' && 'text-blue-400'])}
            data-status="all"
            onClick={() => handleStatus('all')}
            type="button"
          >
            All
          </button>
        </li>
        <li>
          <button
            className={clsx(['link hover:text-blue-400', status === 'pending' && 'text-blue-400'])}
            data-status="pending"
            type="button"
            onClick={() => handleStatus('pending')}
          >
            Active
          </button>
        </li>
        <li>
          <button
            className={clsx(['link hover:text-blue-400', status === 'done' && 'text-blue-400'])}
            data-status="done"
            type="button"
            onClick={() => handleStatus('done')}
          >
            Completed
          </button>
        </li>
      </ul>

      <div />
    </footer>
  );
}
