// apps/react-todoapp/src/components/Item.tsx
/* eslint-disable react/destructuring-assignment */
import clsx from 'clsx';
import { ReactElement } from 'react';

export type Todo = {
  id: string;
  description: string;
  done: boolean;
  createdAt: string;
  doneAt: string | null;
};

export type TodoProps = Todo & {
  handleRemove: () => void;
  handleDone: () => void;
  handleUndone: () => void;
};

export default function Item(todo: TodoProps): ReactElement {
  return (
    <div
      id={todo.id}
      className="flex gap-4 py-1 cursor-pointer text-lg dark:hover:bg-slate-600 hover:bg-slate-100"
      data-type="item"
    >
      <div className="flex items-center gap-2 flex-1">
        <span className={todo.done ? 'text-pink-400' : 'text-blue-400 accent-current'}>
          {todo.description}
        </span>
      </div>

      <div className="grid grid-cols-2 items-center gap-2">
        <span className="text-xs text-gray-300"> {new Date(todo.createdAt).toLocaleString()} </span>
        <span className="text-xs text-green-400">
          {' '}
          {todo.doneAt ? new Date(todo.doneAt).toLocaleString() : null}{' '}
        </span>
      </div>

      <div className="flex gap-1">
        <button
          type="button"
          data-action={todo.done ? 'todo-undone' : 'todo-done'}
          className={clsx([
            'btn btn-circle btn-sm btn-ghost',
            todo.done ? 'hover:bg-fuchsia-400' : 'hover:bg-teal-400',
          ])}
          onClick={todo.done ? todo.handleUndone : todo.handleDone}
        >
          {todo.done ? '✘' : '✔︎'}
        </button>
        <button
          type="button"
          data-action="todo-remove"
          className="btn btn-circle btn-sm btn-ghost hover:bg-red-400"
          onClick={todo.handleRemove}
        >
          🗑
        </button>
      </div>
    </div>
  );
}

// apps/svelte-app/src/lib/Item.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { Todo } from './types/todo';

  export let todo: Todo;

  const dispatch = createEventDispatcher();
</script>

<div
  id={todo.id}
  class="flex gap-4 py-1 cursor-pointer text-lg dark:hover:bg-slate-600 hover:bg-slate-100"
  data-type="item"
>
  <div class="flex items-center gap-2 flex-1">
    <span class={todo.done ? 'text-pink-400' : 'text-blue-400 accent-current'}>
      {todo.description}
    </span>
  </div>

  <div class="grid grid-cols-2 items-center gap-2">
    <span class="text-xs text-gray-300"> {new Date(todo.createdAt).toLocaleString()} </span>
    <span class="text-xs text-green-400">
      {todo.doneAt ? new Date(todo.doneAt).toLocaleString() : ''}
    </span>
  </div>

  <div class="flex gap-1">
    <button
      type="button"
      data-action={todo.done ? 'todo-undone' : 'todo-done'}
      class="btn btn-circle btn-sm btn-ghost"
      class:hover:bg-fuchsia-400={todo.done}
      class:hover:bg-teal-400={!todo.done}
      on:click={() => dispatch(todo.done ? 'undone' : 'done', todo.id)}
    >
      {todo.done ? '✘' : '✔︎'}
    </button>
    <button
      type="button"
      data-action="todo-remove"
      class="btn btn-circle btn-sm btn-ghost hover:bg-red-400"
      on:click={() => dispatch('remove', todo.id)}
    >
      🗑
    </button>
  </div>
</div>
